/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formus;

import ClasesVarias.ClaseUsuario;
import ClasesVarias.Validadores;
import javax.swing.JOptionPane;

/**
 *
 * @author Rolo
 */
public class DatosUsr extends javax.swing.JFrame {
   
   
    /**
     * Creates new form DatosUsr
     */
    public DatosUsr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl1 = new javax.swing.JLabel();
        Lbl2 = new javax.swing.JLabel();
        Lbl3 = new javax.swing.JLabel();
        Lbl4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Lbl5 = new javax.swing.JLabel();
        PassField1 = new javax.swing.JPasswordField();
        PassField2 = new javax.swing.JPasswordField();
        TxtUsr = new javax.swing.JTextField();
        TxtEmail = new javax.swing.JTextField();
        TxtDocum = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Btn_ListarUsr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingreso de Nuevo Usuario ");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(5, 5));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Lbl1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lbl1.setText("NombreUsuario");

        Lbl2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lbl2.setText("Password");

        Lbl3.setText("Email");

        Lbl4.setText("DNI");

        jButton2.setText("Crear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Lbl5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lbl5.setText("Password 2");

        PassField1.setToolTipText("Ingrese Password de Ususario");
        PassField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PassField1FocusGained(evt);
            }
        });
        PassField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassField1ActionPerformed(evt);
            }
        });

        PassField2.setToolTipText("Ingrese Nuevamente el Mismo Password");
        PassField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PassField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PassField2FocusLost(evt);
            }
        });
        PassField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassField2ActionPerformed(evt);
            }
        });

        TxtUsr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtUsrFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtUsrFocusLost(evt);
            }
        });
        TxtUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsrActionPerformed(evt);
            }
        });

        TxtEmail.setToolTipText("Ingrese un Email Personal Valido");
        TxtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtEmailFocusLost(evt);
            }
        });

        TxtDocum.setToolTipText("Ingrese Documento sin puntos ni espacios");
        TxtDocum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtDocumFocusGained(evt);
            }
        });

        Btn_ListarUsr.setText("Listar Usuarios");
        Btn_ListarUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ListarUsrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtDocum, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(PassField1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PassField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(Btn_ListarUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PassField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(Lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PassField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(Lbl3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(Lbl4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtDocum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel1)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(Btn_ListarUsr))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PassField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        //   Instanciar el objeto de la clase usuario
       ClaseUsuario usr = new ClaseUsuario(TxtUsr.getText(), PassField1.getText(), TxtEmail.getText(), TxtDocum.getText());
       Validadores valido = new Validadores();
       String datoIngresado, pass1;
       boolean ResOK;
       
//   Valido Passwords ....
        pass1 = valido.validarPass(PassField1.getPassword(), PassField2.getPassword());
        
        if( pass1.isEmpty()){
            ResOK=false;
            JOptionPane.showMessageDialog(null, "Problemas con el Password Ingresado.");     
        }else 
            ResOK=true;

//   Valido Nombre Usuario ............
      if(ResOK){
         datoIngresado = valido.validarNombreApellido(TxtUsr.getText());
      if( datoIngresado.isEmpty()){    
            ResOK=false;
            JOptionPane.showMessageDialog(null, "Error en el Nombre de Usuario Ingresado.");     
      }else 
            ResOK=true;
      }   
      
//   Valido Email .......
      if(ResOK){
        datoIngresado = valido.validarMail(TxtEmail.getText());
     if( datoIngresado.isEmpty()){    
            ResOK=false;
            JOptionPane.showMessageDialog(null, "Error en el Formato de EMail Ingresado.");     
     }else 
            ResOK=true;
      }

//   Valido Documento ---
//   str.matches("-?\\d+(\\.\\d+)?") para Numero, negativos (-) y Decimal (.)
      if(ResOK){
        if( valido.validarNumeros(TxtDocum.getText().trim(), 8) ){
            ResOK=true;
        }else{
            ResOK=false;
            JOptionPane.showMessageDialog(null, "Error en el Nro. de Documento Ingresado.");     
        }
      }  
      
//  Si esta todo OK . Grabo el Usuario y cierro, Sino Emito mensaje.
      if(ResOK){
          MuestroCarga fr;
          fr = new MuestroCarga();
//  Desactiva el boton de cerrar (X) de la ventana
          fr.setDefaultCloseOperation(MuestroCarga.DO_NOTHING_ON_CLOSE);
          fr.recibodatos(TxtUsr.getText(), pass1.trim(), TxtEmail.getText(), TxtDocum.getText(), usr);
          fr.setVisible(true);
          this.dispose();
      }else {
          JOptionPane.showMessageDialog(null, "Intente nuevamente Ingresando Todos los Datos correctamente.");     
          
      }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TxtUsrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtUsrFocusLost
        // TODO add your handling code here:
     
     
    }//GEN-LAST:event_TxtUsrFocusLost

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:

           
        
        
    }//GEN-LAST:event_formWindowActivated

    private void TxtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtEmailFocusLost
        // TODO add your handling code here:
        TxtEmail.selectAll();

    }//GEN-LAST:event_TxtEmailFocusLost

    private void PassField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PassField2FocusLost
        // TODO add your handling code here:

        
    }//GEN-LAST:event_PassField2FocusLost

    private void PassField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PassField1ActionPerformed

    private void TxtUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsrActionPerformed

    private void TxtUsrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtUsrFocusGained
        // TODO add your handling code here:
        TxtUsr.selectAll();
    }//GEN-LAST:event_TxtUsrFocusGained

    private void PassField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PassField1FocusGained
        // TODO add your handling code here:
        PassField1.selectAll();
    }//GEN-LAST:event_PassField1FocusGained

    private void PassField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PassField2FocusGained
        // TODO add your handling code here:
        PassField2.selectAll();
    }//GEN-LAST:event_PassField2FocusGained

    private void TxtDocumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtDocumFocusGained
        // TODO add your handling code here:
        TxtDocum.selectAll();
    }//GEN-LAST:event_TxtDocumFocusGained

//
//  Teniendo en cuenta que los  JFrame no pueden ser Modales (JDialog si)
//  Uso JDialog como formulario para mostrar los Usuarios Creados  
//
    private void Btn_ListarUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ListarUsrActionPerformed
        // TODO add your handling code here:
        // Instancio el frmDialog :
        ListadoUsuarios todosdiag = new ListadoUsuarios(this,true);  // frmDialogo(this,true);
        // Evito que cierre la ventan con el icono X :
        todosdiag.setDefaultCloseOperation(ListadoUsuarios.DO_NOTHING_ON_CLOSE);
        // Llamo al Metodo en el JDialog y lo hago visible :
        todosdiag.Cargo_Tabla();
        todosdiag.setVisible(true);
 //        this.dispose();
        
    }//GEN-LAST:event_Btn_ListarUsrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosUsr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosUsr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosUsr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosUsr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosUsr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_ListarUsr;
    private javax.swing.JLabel Lbl1;
    private javax.swing.JLabel Lbl2;
    private javax.swing.JLabel Lbl3;
    private javax.swing.JLabel Lbl4;
    private javax.swing.JLabel Lbl5;
    private javax.swing.JPasswordField PassField1;
    private javax.swing.JPasswordField PassField2;
    private javax.swing.JTextField TxtDocum;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtUsr;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
