/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formus;

import ClasesVarias.Validadores;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rolo
 */
public class ListadoUsuarios extends javax.swing.JDialog {

    /**
     * Creates new form ListadoUsuarios
     */
    public ListadoUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        T_ListadoUs = new javax.swing.JTable();
        Btn_Salida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        T_ListadoUs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Password", "MAIL", "DNI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        T_ListadoUs.setName(""); // NOI18N
        T_ListadoUs.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                T_ListadoUsFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(T_ListadoUs);

        Btn_Salida.setText("Salir");
        Btn_Salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SalidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 55, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(Btn_Salida)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Btn_Salida)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void T_ListadoUsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_T_ListadoUsFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_T_ListadoUsFocusGained

    private void Btn_SalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SalidaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Btn_SalidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListadoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListadoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListadoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListadoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ListadoUsuarios dialog = new ListadoUsuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
//   ...  Cargo la JTable con los Usuarios Creados ....
    public void Cargo_Tabla(){
       // Instancio objeto de clase validadores
        Validadores valido = new Validadores();

//  Defino la Tabla en Modo DefaultTableModel para que sea mas facil manejarlo
        DefaultTableModel modelo = new DefaultTableModel();
//        Defino los titulos de Columnas;
        modelo.addColumn("USUARIO");
        modelo.addColumn("PASSWORD");
        modelo.addColumn("EMAIL");
        modelo.addColumn("DNI");
        
//      Asigno una fila a la Tabla; aca leer del archivo
//      modelo.addRow(new Object[] {"Usuario", "Contrasena","Correo", "Documento"});
//      Tambien se puede agregar un Dato de la siguiente forma: 
//        T_ListadoUs.setValueAt(Dato, Fila, Columna);

//   Genero variable para lectura del Directorio
        String ruta="E:\\EjerciciosProg\\Java\\";
        File dir = new File(ruta);
        if (dir.exists()){
//      Si Existe, cargo el contenido del path
            File[] Archivos = dir.listFiles() ;
            if(Archivos != null){
              String nombre;
              String[] datosarch;
              int lin = 4;
              for(int x=0;x<Archivos.length;x++){
//            Verifico que sea un Txt
                  if(Archivos[x].getName().endsWith("txt")){
                   nombre = Archivos[x].getName();
//            Cargar el Array                
                   datosarch = valido.Leo_Archivo(ruta, nombre, lin);
//            Cargar al Jtable                
                   modelo.addRow(new Object[] {datosarch[0], datosarch[1], datosarch[2], datosarch[3]});
                 }
               }
//         Paso valores a la Tabla
           T_ListadoUs.setModel(modelo);
            }else{
		JOptionPane.showMessageDialog(null, "No hay Archivos en el Directorio: " + ruta + " Seleccionado. Verifique. ");            
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se encontro el Directorio: " + ruta + " . Verifique. ");            
            
        }
//  --------------------------        
    }
        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Salida;
    private javax.swing.JTable T_ListadoUs;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
